export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const GET_FROM_SESSION_STATE = 'GET_FROM_SESSION_STATE';
export const SELECTED_DOCTYPE_CONTENT_PAGE = 'SELECTED_DOCTYPE_CONTENT_PAGE';
export const SET_ALL_DATATYPES = 'SET_ALL_DATATYPES';
export const SET_DATATYPE = 'SET_DATATYPE';
export const REMOVE_DATATYPE_FROM_DOCTYPE = 'REMOVE_DATATYPE_FROM_DOCTYPE';
