export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const GET_FROM_SESSION_STATE = 'GET_FROM_SESSION_STATE';
export const SELECTED_DOCTYPE_CONTENT_PAGE = 'SELECTED_DOCTYPE_CONTENT_PAGE';
